from log_parsers import Event, Parser


class AuditEvent(Event):
    """Event logged by `auditd`"""

    def __init__(self, **kwargs) -> None:
        super().__init__(**kwargs)


class AuditParser(Parser):
    """Parser for logs generated by `auditd`"""

    def __init__(self, filepath: str) -> None:
        super().__init__(filepath)
